package fhir

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
)

// FHIRResourceTypes is the canonical set of all FHIR R4 resource type names.
// Each key is a valid resource type; the value is always true.
var FHIRResourceTypes = map[string]bool{
	"Account":                          true,
	"ActivityDefinition":               true,
	"AdverseEvent":                     true,
	"AllergyIntolerance":               true,
	"Appointment":                      true,
	"AppointmentResponse":              true,
	"AuditEvent":                       true,
	"Basic":                            true,
	"Binary":                           true,
	"BiologicallyDerivedProduct":       true,
	"BodyStructure":                    true,
	"Bundle":                           true,
	"CapabilityStatement":              true,
	"CarePlan":                         true,
	"CareTeam":                         true,
	"CatalogEntry":                     true,
	"ChargeItem":                       true,
	"ChargeItemDefinition":             true,
	"Claim":                            true,
	"ClaimResponse":                    true,
	"ClinicalImpression":              true,
	"CodeSystem":                       true,
	"Communication":                    true,
	"CommunicationRequest":             true,
	"CompartmentDefinition":            true,
	"Composition":                      true,
	"ConceptMap":                       true,
	"Condition":                        true,
	"Consent":                          true,
	"Contract":                         true,
	"Coverage":                         true,
	"CoverageEligibilityRequest":       true,
	"CoverageEligibilityResponse":      true,
	"DetectedIssue":                    true,
	"Device":                           true,
	"DeviceDefinition":                 true,
	"DeviceMetric":                     true,
	"DeviceRequest":                    true,
	"DeviceUseStatement":               true,
	"DiagnosticReport":                 true,
	"DocumentManifest":                 true,
	"DocumentReference":                true,
	"EffectEvidenceSynthesis":          true,
	"Encounter":                        true,
	"Endpoint":                         true,
	"EnrollmentRequest":                true,
	"EnrollmentResponse":               true,
	"EpisodeOfCare":                    true,
	"EventDefinition":                  true,
	"Evidence":                         true,
	"EvidenceVariable":                 true,
	"ExampleScenario":                  true,
	"ExplanationOfBenefit":             true,
	"FamilyMemberHistory":              true,
	"Flag":                             true,
	"Goal":                             true,
	"GraphDefinition":                  true,
	"Group":                            true,
	"GuidanceResponse":                 true,
	"HealthcareService":                true,
	"ImagingStudy":                     true,
	"Immunization":                     true,
	"ImmunizationEvaluation":           true,
	"ImmunizationRecommendation":       true,
	"ImplementationGuide":              true,
	"InsurancePlan":                    true,
	"Invoice":                          true,
	"Library":                          true,
	"Linkage":                          true,
	"List":                             true,
	"Location":                         true,
	"Measure":                          true,
	"MeasureReport":                    true,
	"Media":                            true,
	"Medication":                       true,
	"MedicationAdministration":         true,
	"MedicationDispense":               true,
	"MedicationKnowledge":              true,
	"MedicationRequest":                true,
	"MedicationStatement":              true,
	"MedicinalProduct":                 true,
	"MedicinalProductAuthorization":    true,
	"MedicinalProductContraindication": true,
	"MedicinalProductIndication":       true,
	"MedicinalProductIngredient":       true,
	"MedicinalProductInteraction":      true,
	"MedicinalProductManufactured":     true,
	"MedicinalProductPackaged":         true,
	"MedicinalProductPharmaceutical":   true,
	"MedicinalProductUndesirableEffect": true,
	"MessageDefinition":                true,
	"MessageHeader":                    true,
	"MolecularSequence":                true,
	"NamingSystem":                     true,
	"NutritionOrder":                   true,
	"Observation":                      true,
	"ObservationDefinition":            true,
	"OperationDefinition":              true,
	"OperationOutcome":                 true,
	"Organization":                     true,
	"OrganizationAffiliation":          true,
	"Parameters":                       true,
	"Patient":                          true,
	"PaymentNotice":                    true,
	"PaymentReconciliation":            true,
	"Person":                           true,
	"PlanDefinition":                   true,
	"Practitioner":                     true,
	"PractitionerRole":                 true,
	"Procedure":                        true,
	"Provenance":                       true,
	"Questionnaire":                    true,
	"QuestionnaireResponse":            true,
	"RelatedPerson":                    true,
	"RequestGroup":                     true,
	"ResearchDefinition":               true,
	"ResearchElementDefinition":        true,
	"ResearchStudy":                    true,
	"ResearchSubject":                  true,
	"RiskAssessment":                   true,
	"RiskEvidenceSynthesis":            true,
	"Schedule":                         true,
	"SearchParameter":                  true,
	"ServiceRequest":                   true,
	"Slot":                             true,
	"Specimen":                         true,
	"SpecimenDefinition":               true,
	"StructureDefinition":              true,
	"StructureMap":                     true,
	"Subscription":                     true,
	"Substance":                        true,
	"SubstanceNucleicAcid":             true,
	"SubstancePolymer":                 true,
	"SubstanceProtein":                 true,
	"SubstanceReferenceInformation":    true,
	"SubstanceSourceMaterial":          true,
	"SubstanceSpecification":           true,
	"SupplyDelivery":                   true,
	"SupplyRequest":                    true,
	"Task":                             true,
	"TerminologyCapabilities":          true,
	"TestReport":                       true,
	"TestScript":                       true,
	"ValueSet":                         true,
	"VerificationResult":               true,
	"VisionPrescription":               true,
}

// IsValidResourceType checks whether the given name is a valid FHIR R4 resource type.
func IsValidResourceType(name string) bool {
	return FHIRResourceTypes[name]
}

// ValidateResourceType checks if resourceType is a valid FHIR R4 resource type and
// returns a 404 JSON response with an OperationOutcome if it is not. Returns nil when
// the resource type is valid.
func ValidateResourceType(c echo.Context, resourceType string) error {
	if FHIRResourceTypes[resourceType] {
		return nil
	}
	return c.JSON(http.StatusNotFound, NewOperationOutcome(
		IssueSeverityError,
		IssueTypeNotFound,
		fmt.Sprintf("resource type '%s' is not a known FHIR R4 resource type", resourceType),
	))
}
